package errorresponse

const (
	CommonKeyNameIsRequired              = "Tên không được để trống"
	CommonKeyEmailIsRequired             = "Email không được để trống"
	CommonKeyPasswordIsRequired          = "Mật khẩu không được để trống"
	CommonKeyTokenAuthenticationExpired  = "Token đã hết hạn"
	CommonKeyStaffNotActive              = "Tài khoản đã bị khóa"
	CommonKeyNotHavePermission           = "Không có quyền truy cập"
	CommonKeyAccountNotFound             = "Tài khoản không tồn tại"
	CommonKeyPasswordNotMatch            = "Mật khẩu không đúng"
	CommonKeyPageInvalid                 = "Trang không hợp lệ"
	CommonKeyLimitInvalid                = "Giới hạn không hợp lệ"
	CommonKeyPriceIsRequired             = "Giá không được để trống"
	CommonKeyQuantityIsRequired          = "Số lượng không được để trống"
	CommonKeyDescriptionIsRequired       = "Mô tả không được để trống"
	CommonKeyImageIsRequired             = "Hình ảnh không được để trống"
	CommonKeyErrFileNotValid             = "File không hợp lệ"
	CommonKeyErrUserNotValid             = "Người dùng không hợp lệ"
	CommonKeyErrReadFile                 = "Đọc file thất bại"
	CommonKeyErrUploadFile               = "Upload file thất bại"
	CommonKeyErrResizeImage              = "Resize ảnh thất bại"
	CommonKeyNameIDIsRequired            = "NameID không được để trống"
	CommonKeyIntroduceNotFound           = "Giới thiệu không tồn tại"
	CommonKeyNameIdIsRequired            = "NameId không được để trống"
	CommonKeyPhoneIsRequired             = "Số điện thoại không được để trống"
	CommonKeyAddressIsRequired           = "Địa chỉ không được để trống"
	CommonKeyGoogleMapUrlEmbebIsRequired = "Google Map Url Embeb không được để trống"
	CommonKeyUnitIsRequired              = "Đơn vị không được để trống"
	CommonKeyParIDIsRequired             = "ParID không được để  trống"
	CommonKeyTitleIsRequired             = "Tiêu đề  không được để  trống"
	CommonKeyContentIsRequired           = "Nội dung không được để  trống"
	CommonKeyPassIsRequired              = "Mật khẩu phải nhập"
)
